### ISSUE TITLE
Constructor interface.

### ISSUE THREAD

**Issue by reedHam** [surrealdb/surrealdb.deno#3]
The current deno class interface  requires a token. 

https://github.com/surrealdb/surrealdb.deno/blob/675705de6aa0130449b19f1c3c2f8491bcc2188f/src/mod.ts#L70

```typescript
const DB = new Surreal("https://localhost:8000/rpc"); // <<- type error token required.
```

I have to add an empty string to get it to compile.
```typescript
const DB = new Surreal("https://localhost:8000/rpc", "");
```

This does not match the documents on https://surrealdb.com/docs/integration/libraries/deno

**Comment by W4G1** [comment]
This is a typescript issue and since there are no types, we have to wait until they are added.

In the meantime you can also do this:
```typescript
const DB = new Surreal("https://localhost:8000/rpc", undefined);
```
